os: linux
dist: bionic
sudo: required
language: bash

before_script:
- sudo apt update
- sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64

script:
- bash build.sh

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  provider: releases
  api_key:
    secure: iqmt0/JGzw+QXQwth/gla1M6KA0aOgYuCQEBjaRMNmtLAJn96Nn6qWGvbubrrjlcEPGNC1S6r2fx1MkPz+MvoOpGWohQ3Jxr+5+kARmNa2GlxuaLJpH5VNqqpVswGWrqrwOYV5NzdrPxnq4dXX8rFaeHAL1XykFzIxLQqadzr1inBknuhSY6vaqCawXLC+2+H7J4wvGSyw6o3G0LGBEljAxYeBVRHuDXOnP3XfooRQLw/brqIm9d1ZGhaBqNN22qiBqCuvEjvFGQf27YCzIad6oyU0zdsvvauZRKzosCBqEW353Ww6HOIrAaZW98U6GdWkFAqzB4vDznrQUu9ybiDyQTIuK/yYrA7kGM5R2Vi7ZGoR6qatF005vZhqjXQP5GH7TcTCOiZeYyyR91cF66Bf7Olxjs0UloiBYZWNUZ7E99VkJ7S/8hiYr+epSjdHdF9KmLY7GTp7iBq0aV89MCgz6LNYBd3Yoh1Ll/72WYwomaeAAg32K6Z7yFPym+3lMQ4h7SY4QAmHrQKr/qD3gJZTlBWsl/i/R8+6lcRZ5napSJJiS3knToEJMs9Y3N+grk04C3Xtigy3to7XLXSIseVYa2aLf1DtPKi3Nti2IHjOvYhR9pU5hfo272zNb3bfpBLLoMR4FqFquphPYT/X0Saakv7zQ3/EoUEcdcUqOMIqg=
  file: output/final/*.tar.xz
  skip_cleanup: true
  overwrite: true
  on:
    repo: simelo/skybian
    branch: develop
    tags: true