os: linux
dist: bionic
sudo: required
language: bash

before_script:
  - sudo apt update
  - sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64

script: 
  - bash build.sh

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
