os: linux
dist: bionic
sudo: required
language: bash

before_script:
- sudo apt update
- sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64

script:
- bash build.sh

notifications:
  email:
  - false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_deploy:
- bash build.sh -p

deploy:
  provider: releases
  api_key:
    secure: lT1yxdNZmEoUnZ8JudQesogLSjl/KSW8iltx4XFqWivA5CUMHakfMaJ8+FH2kFRNFm/nYZzR5L8srJT2GJxjkkxVSdnRGxq2isY7/fkbQBaKSNpbxb46D5fQNVLJKluc0hS7mKJsVgAqHNTsoyzS7vcrehjBVaSmUoZ7Hhi2rdKqU0h7cf+FzxTCUg3/I5ZiQmFhxyU6H+FnwLGF4FcrX5sxO2OS7rxBuaGYuSkR0fmRYfsq8Lfr7NxTYtiPl3UE0dlmPA/TLoWrozaVwhWS+v1onIMVkz1hu5BTZNu8l09GXpRFyZ/+CJtyuRijq7r7PtUGUQdpA5x0CElvWeZARFTjowu5JDnH7owmA5sbWpGy1h4egTirlHtt/jvH+sim325ummivtYVJlNbo38VYYE2a+IvUTCeqz0UYtxtifa2nOjciwYfa+mHVUIWRlVGAM0U/k3eT3Iv/NV/SO7NW81+QEbiLUcKhlJXGa2GUOOf3oFcDDzHrq38dUr7hYeg5WKC/KZAftgtF3K+7AKExZHgBAfB7g6mVh8LQcJ9tI2VNuWWkXe+HqykYcnmaW/5hLiz0ORZssblJrAVyk2rLc2h4n+xJo8lo4EzmlSbhp/3xs+Bq5s7XwPab3Ubjr/2MdoNGkwVagbxB7Dplr7WS+DC7O0NuMJQcsyUUQEP3czU=
  file_glob: true
  file: "output/final/*.xz"
  draft: true
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master$|^release-.*$"
