os: linux
dist: bionic
sudo: required
language: bash

before_script:
- sudo apt update
- sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64

script:
- bash build.sh

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  provider: releases
  user: stdevPavelmc
  password:
    secure: kQ+WkYUjptHIulwBBuGX4DHctxVRiNQqQ/t6FHheN+q1iRnALJfltNF/eNQKQfOay9Mn3cfSrlnOVW70IxYptz4BtMrVxq610MUmjVO9/mTNlQv0ZU6fF1IFa+B3roL4qXS8Hnln+PUKFlAzPTuSUv5D2OKvI3fOFeRoW0TaaShJJit2c9Xg5cTD8NlKPtv1DKLgdA1bml3oHOR3ZXmzfuIiTfP+l1wDAb/e104V3B4WJkDi7aSiCwZqXRYby0KUpmr2VSvgr7t324c7UGyTlGiWxdkuvcagS200m6hkeMF/d1Hga30+tx6RStVfWWHA+0DSunA2ZAp4dWlnFrrYCvUGINDDG4WQ+S/rPSgCY8S06qtsXpNux1tIW+iHzDs8ht/SCO76YCduEpHFjOvqiXs3TJdgl9l8wDOatL5Cc34xaf8nQNlYLcgA7oBKAxArzoDFL8/bmLhTyTw651f9Ru3kDAgPOQeLjzuhJfUA9AacfeXVbbtcEns6C1wNPWs2g3+C+pzZuQbrTqKzlAQwgfqF5vqJrYDbVqiL0F0zFzjlr8Klik6y1gBpMHw4LGksX8QC61EFCFEdSjZ9o+lfdlpoUVw/NvF8Paha4gvd4APufK+OdFWaQdLeAdVkyefYuh6kqQpIJlYbw9W4jm7soiBqaBNuL7dQYyA7+C6gitI=
  file_glob: true
  file: output/final/*.xz
  skip_cleanup: true
  overwrite: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|release$"
    draft: true
