os: linux
dist: bionic
sudo: required
language: bash

before_script:
- sudo apt update
- sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64

script:
- bash build.sh

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_deploy:
- bash build.sh -p

deploy:
  provider: releases
  api_key:
    secure: lBSUOmVQRWTn8UrsXa5HcXbvJn8NAvK++IXAiun8h9ne1maRHjjhtbA8dYHEzt0HUxNbdwubRI2Lr+f0QksxL7+d5dn3zNEowMo+sAqiGR2e9i94GAdfbd0XD7OdqUykiPB3VXvcXpum1oCKbzkStddrURIZCy8nLU1NfApA1vqZyyTisFGUdy1bYF+ogmaFIZ6r5PUNpm3iLFLMP3+aMQGmoohfCDWcNAyFeS9R40cSk9exqr141nnsIU1pByuV0WjikSQAOrGfjIekjP86klz0AJ7wxyqG3L4VGqvQisHRzOQnQOBvc4T53EAm/Mw/5HRGCwG/GRHkZSefPiM1dXMtFJFz3qMJSngU4uHjjLhUg5IfqOoIbhSgGmvc2YfuDvzx0Gqj8FwPlNjX/fMq3Z4snTH52JBYhaiT+AL1UIaI3AuhlzNlJ4sIteob/wBajVM5HxX3q+rnqorPSPftQ5AqnUY9s+/Fx/S8PcTfo7tOYbrtvcEtDDipvZC1Gd3vbZ+Quxs2gc7PcyRwHu2q8DQ2wNFRTqLqou2PUqvhTXMcQiZlO/x4jXZ5HGDuOb8ggAcuks1A46IVDnMVGmXK76vOplBWoePlEvHd5eIGhA4nZ5buIyeot8r7QSPTDQ0D2RXmL7qqpAtA9O/yake8/96esprxdYF/mDjHwhvWlPY=
  file_glob: true
  file: "output/final/*.xz"
  draft: true
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master$|^release-.*$"
