os: linux
dist: bionic
sudo: required
language: bash

before_script:
  - sudo apt update
  - sudo apt install -y p7zip-full qemu-user-static build-essential crossbuild-essential-arm64

script: 
  - bash build.sh

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  provider: releases
  api_key: ""
  file_glob: true
  file: output/final/*.img
  skip_cleanup: true
  overwrite: true
  on:
    branch: develop
    tags: true
